Access Control Options 🔒
poki/mongodb-filter-to-postgres pull request #29
Opened 2024-10-11 14:37 UTC by koenbollen

Adding access control options, making the converter error if a disallowed column/field is queried.

Previously this library has been insecure by default, users could easily make the mistake of opening up their entire database. This change makes it required to supply at least one access control option.

New options:
- `filter.WithAllowAllColumns()`  
  Allow filtering of all columns, same as the previous behaviour
- `filter.WithAllowColumns(...)`  
  Allow only selected columns
- `filter.WithDisallowColumns(...)`  
  Disallow certain columns, used in combination with WithAllowAllColumns() and WithNestedJSONB().

Note: This change is not backwards compatible! ⚠️

2024-10-11 14:38 UTC, koenbollen commented on filter/converter_test.go
> +	t.Skip() // this is currently not supported since we introduced the access control options
@erikdubbelboer, I'm not sure how to handle this. Do you have an idea how we can still support bare struct usage?

2024-10-16 07:40 UTC, erikdubbelboer requested changes
You forgot this one causing the integration test to panic (because the converter is nil): https://github.com/poki/mongodb-filter-to-postgres/blob/0eb6853c6ec2c50fc1826ebf9e66f66c76750ab5/integration/postgres_test.go#L188

2024-10-16 07:40 UTC, erikdubbelboer commented on filter/converter_test.go
> +	t.Skip() // this is currently not supported since we introduced the access control options
I don't think we can, so let's just not.

2024-10-18 08:44 UTC, koenbollen commented on filter/converter_test.go
> +	t.Skip() // this is currently not supported since we introduced the access control options
I've updated the test.

2024-10-18 08:55 UTC, erikdubbelboer submitted a review, later dismissed

2024-10-19 09:08 UTC, erikdubbelboer approved these changes

2024-10-19 09:08 UTC, merged